labpr/urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]


urlpatterns += staticfiles_urlpatterns()

website/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record, Test

class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))


	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	








class AddRecordForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"First Name", "class":"form-control"}), label="")
    last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Last Name", "class":"form-control"}), label="")
    phone = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Phone", "class":"form-control"}), label="")
    total_price = forms.IntegerField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Price For Customer", "class":"form-control"}), label="")
    lab_choices = [
        ('lab1', 'Lab 1'),
        ('lab2', 'Lab 2'),
        ('lab3', 'Lab 3'),
        ('lab4', 'Lab 4'),
        ('lab5', 'Lab 5')
    ]
    lab = forms.ChoiceField(choices=lab_choices, widget=forms.Select(attrs={"class": "form-control"}), required=True, label="Lab")
    tests = forms.ModelMultipleChoiceField(queryset=Test.objects.all(), required=False, widget=forms.widgets.CheckboxSelectMultiple)
    paid = forms.ChoiceField(choices=(('paid', 'Paid'), ('udhaar', 'Udhaar')), widget=forms.widgets.RadioSelect(), required=True, label='Payment Option')



    class Meta:
        model = Record
        exclude = ("user",)

    def __init__(self, *args, **kwargs):
        super(AddRecordForm, self).__init__(*args, **kwargs)
        tests = Test.objects.all()
        for test in tests:

            self.fields['tests'].widget.attrs['data-price'] = test.Price
            


		



class ProductForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['code', 'testname', 'Price']

templates/add_product.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Add Record</h1>
    <br/>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Product</button>
</form>



{% endblock %}

templates/add_record.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>


<div class="col-md-8 offset-md-3">
<h1>Add Record</h1>
<br/>

<form method="POST" action="{% url 'add_record' %}" class="formscss">
	{% csrf_token %}


  {% for field in form %}
    {% if field.field.name == 'tests' %}
        {% for test in field.field.queryset %}
            <p>
                <label for="{{ field.id_for_label }}">
                    <input type="checkbox" id="{{ field.id_for_label }}" name="{{ field.name }}" value="{{ test.code }}" data-price="{{ test.Price }}">
                    {{ test.testname }} - ${{ test.Price }}
                </label>
            </p>
        {% endfor %}
    {% else %}
        <p> {{ field }}</p>
    {% endif %}
{% endfor %}

<br/>

<p id="total-price">Total Price: 0</p>
  <button type="submit" class="btn btn-secondary">Add Record</button>
   <a href="{% url 'home' %}" class="btn btn-secondary">Back</a>

</form>

</div>

<script>
  $(document).ready(function() {
      $('input[type="checkbox"]').change(function() {
          var total = 0;
          $('input[type="checkbox"]:checked').each(function() {
              total += parseInt($(this).attr('data-price'));
          });
          $('#total-price').text('Total Price: ' + total);
      });
  });
  </script>
  

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
  <style>
form {
    display: grid;
    grid-template-columns: auto 1fr; /* First column takes the width of its content, second column takes remaining space */
    gap: 20px; /* Gap between columns */
}

#id_first_name, #id_last_name{
  margin-top: -120px;
}

#id_phone{
  margin-top: -100px;
}

#id_lab{
  margin-top: -80px;
}
#id_total_price{
  margin-top: -60px;
}
#id_paid{
  margin-top: -80px;
}

#total-price{
  margin-top: -90px;
}

#id_tests {
    display: grid;
    grid-template-columns: repeat(4, 1fr); /* Creates four columns with equal width */
    gap: 2px; 
    margin-left: -300px;
    /* Adjust the gap between columns */
  }


#id_tests {
    grid-column: 1; /* Place id_tests in the first column */
}

/* Ensuring other elements take the second column */
form > *:not(#id_tests) {
    grid-column: 2;
     /* Place other elements in the second column */
}

/* Additional styling to make the layout more appealing */
label {
    display: block; /* Ensure labels take full width */
}

/* Adjusting input widths */
input[type="text"],
select,
input[type="number"] {
    width: 100%; /* Make input fields take full width */
}

  </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
      <br/>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>


        {% endfor %}
      {% endif %}
      
      {% block content %}
      {% endblock%}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}



{% if user.is_authenticated %}


{% if records %}
    <!-- Search Form -->
    <form method="GET" action="{% url 'search_records' %}">
        <input type="text" name="query" placeholder="Search...">
        <button type="submit">Search</button>
    </form>



    {% regroup records by created_at|date:"Y-m-d" as grouped_records %}
    {% for group in grouped_records reversed %}
        <h2>{{ group.grouper }}</h2>
        <table class="table table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Lab</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Paid</th>

                </tr>
            </thead>
            <tbody>
                {% for record in group.list reversed %}
                    <tr>
                        <td><a href="{% url 'record' record.id %}">{{ record.first_name }} {{ record.last_name }}</a></td>
                        <td>{{ record.phone }}</td>
                        <td>{{ record.lab }}</td>
                        <td>{{ record.total_price }}</td>
                        <td>{{ record.paid }}</td>
                        {% if record.paid == "udhaar" %}
                            <td><a href="{% url 'pay_option' record.id %}">Pay</a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}

{% endif %}




	
	  </tbody>
	</table>





{% else %}

<div class="col-md-6 offset-md-3">
<h1>Login</h1>
<br/>

<form method="POST" action="{% url 'home' %}">
	{% csrf_token %}

  <div class="mb-3">
    <input type="text" class="form-control" name="username", placeholder="Username" required>
    
  </div><br/>
  <div class="mb-3">
    <input type="password" class="form-control" name="password", placeholder="Password" required>
  </div>
  <br/>
  <button type="submit" class="btn btn-secondary">Login</button>

</form>



{% endif %}

{% endblock %}

templates/lab_records.html
{% extends 'base.html' %}

{% block content %}



{% if user.is_authenticated %}


{% if records %}
{% regroup records by created_at|date:"Y-m" as grouped_records %}

    {% for group in grouped_records reversed %}
        <h2>{{ group.grouper }} <a href = "{% url 'generate_pdf' month=group.grouper lab=lab %}">Download PDF</a></h2>
        <table class="table table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Lab</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Paid</th>

                </tr>
            </thead>
            <tbody>
                {% for record in group.list reversed %}
                    <tr>
                        <td><a href="{% url 'record' record.id %}">{{ record.first_name }} {{ record.last_name }}</a></td>
                        <td>{{ record.phone }}</td>
                        <td>{{ record.lab }}</td>
                        <td>{{ record.total_price }}</td>
                        <td>{{ record.paid }}</td>
                        {% if record.paid == "udhaar" %}
                            <td><a href="{% url 'pay_option' record.id %}">Pay</a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}

{% endif %}




	
	  </tbody>
	</table>





{% else %}

<div class="col-md-6 offset-md-3">
<h1>Login</h1>
<br/>

<form method="POST" action="{% url 'home' %}">
	{% csrf_token %}

  <div class="mb-3">
    <input type="text" class="form-control" name="username", placeholder="Username" required>
    
  </div><br/>
  <div class="mb-3">
    <input type="password" class="form-control" name="password", placeholder="Password" required>
  </div>
  <br/>
  <button type="submit" class="btn btn-secondary">Login</button>

</form>



<script>
    function downloadPDF(month) {
        // Send an AJAX request to the server to generate the PDF for the selected month
        var xhr = new XMLHttpRequest();
        xhr.open('GET', '/generate_pdf/?month=' + month, true);
        xhr.responseType = 'blob';

        xhr.onload = function() {
            if (xhr.status === 200) {
                // Create a blob URL for the response data
                var blob = new Blob([xhr.response], {type: 'application/pdf'});
                var url = window.URL.createObjectURL(blob);

                // Create a temporary link element and trigger a click event to download the PDF
                var a = document.createElement('a');
                a.href = url;
                a.download = 'records_' + month + '.pdf';
                document.body.appendChild(a);
                a.click();

                // Cleanup
                window.URL.revokeObjectURL(url);
                document.body.removeChild(a);
            }
        };

        xhr.send();
    }
</script>




{% endif %}

{% endblock %}

templates/labs_list.html
<!-- labs_list.html -->
{% extends 'base.html' %}

{% block content %}



{% if user.is_authenticated %}



    <h1>Labs</h1>
    <ul>
        {% for lab in labs %}
            <li><a href="{% url 'lab_records' lab=lab %}">{{ lab }}</a></li>
        {% endfor %}
    </ul>
    {% else %}

    <div class="col-md-6 offset-md-3">
    <h1>Login</h1>
    <br/>
    
    <form method="POST" action="{% url 'home' %}">
        {% csrf_token %}
    
      <div class="mb-3">
        <input type="text" class="form-control" name="username", placeholder="Username" required>
        
      </div><br/>
      <div class="mb-3">
        <input type="password" class="form-control" name="password", placeholder="Password" required>
      </div>
      <br/>
      <button type="submit" class="btn btn-secondary">Login</button>
    
    </form>
    
    
    
    {% endif %}
    
    {% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Ashish Lab</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_record' %}">Add Record</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_product' %}">Add Test</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'udhaar' %}">Udhaar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'labs_list' %}">Labs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Login</a>
        </li>        
        {% endif %}
        
        
      </ul>
      
    </div>
  </div>
</nav>

templates/product_list.html
{% extends 'base.html' %}
{% block content %}

<!-- product_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product List</title>
</head>
<body>
    <h1>Product List</h1>
    <ul>
        {% for product in products %}
            <li>{{ product.code }} - {{ product.testname }}- {{ product.Price }}</li>
        {% endfor %}
    </ul>
</body>
</html>

{% endblock %}

templates/record.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>


<div class="card">
  <div class="card-header"><strong>
    	{{ customer_record.first_name }} 
		{{ customer_record.last_name }}</strong>
  </div>
  <div class="card-body">





<p class="card-text">
<strong>Phone: </strong>{{ customer_record.phone }}
</p>



<p class="card-text">
<strong>Total Price: </strong>{{ customer_record.total_price }}</p>

<p class="card-text">
<strong>Create At: </strong>{{ customer_record.created_at }}</p>




<p class="card-text">
  <strong>Lab: </strong>{{ customer_record.lab }}</p>

<p><strong>Tests:</strong></p>
<ul>
  {% for test in customer_record.tests.all %}
      <li>{{ test.testname }}</li>
  {% endfor %}
</ul>
    
    
  </div>
</div>

<br/><br/>
<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>

<a href="{% url 'delete_record' customer_record.id %}" class="btn btn-danger">Delete</a>

<a href="{% url 'update_record' customer_record.id %}" class="btn btn-secondary">Update Record</a>


		

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}


<div class="col-md-6 offset-md-3">
<h1>Register</h1>
<br/>

<form method="POST" action="">
	{% csrf_token %}
	{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Your Form Has Errors
			  {% for field in form %}
			  	{% if field.errors %}
			  		{{ field.errors }}
			  	{% endif %}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

	{{ form.as_p }}

	<br/>
	  <button type="submit" class="btn btn-secondary">Register</button>
	</form>



</div>

{% endblock %}

templates/udhaar.html
{% extends 'base.html' %}

{% block content %}



{% if user.is_authenticated %}


{% if records %}
    {% regroup records by created_at|date:"Y-m-d" as grouped_records %}
    {% for group in grouped_records reversed %}
        <h2>{{ group.grouper }}</h2>
        <table class="table table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Lab</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Paid</th>

                </tr>
            </thead>
            <tbody>
                {% for record in group.list reversed %}
                {% if record.paid == "udhaar" %}
                    <tr>
                        <td><a href="{% url 'record' record.id %}">{{ record.first_name }} {{ record.last_name }}</a></td>
                        <td>{{ record.phone }}</td>
                        <td>{{ record.lab }}</td>
                        <td>{{ record.total_price }}</td>
                        <td>{{ record.paid }}</td>
                        
                            <td><a href="{% url 'pay_option2' record.id %}">Pay</a></td>
                        
                    </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}

{% endif %}




	
	  </tbody>
	</table>





{% else %}

<div class="col-md-6 offset-md-3">
<h1>Login</h1>
<br/>

<form method="POST" action="{% url 'home' %}">
	{% csrf_token %}

  <div class="mb-3">
    <input type="text" class="form-control" name="username", placeholder="Username" required>
    
  </div><br/>
  <div class="mb-3">
    <input type="password" class="form-control" name="password", placeholder="Password" required>
  </div>
  <br/>
  <button type="submit" class="btn btn-secondary">Login</button>

</form>



{% endif %}

{% endblock %}

templates/update_record.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
<h1>Add Record</h1>
<br/>

<form method="POST">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
  <button type="submit" class="btn btn-secondary">Update Record</button>

</form>


</div>

{% endblock %}